### ISSUE TITLE
pelican content   CRITICAL: TemplateSyntaxError: Encountered unknown tag 'assets'.

### ISSUE THREAD

**Issue by pcwuyu** [kura/eevee#1]
please help me to solve this~
-  pelican content  
CRITICAL: TemplateSyntaxError: Encountered unknown tag 'assets'.
![pelican content  ](https://cloud.githubusercontent.com/assets/6291329/16409186/de343292-3d4e-11e6-813b-23fb991c4474.png)
- cat pelicanconf.py
![cat pelicanconf.py](https://cloud.githubusercontent.com/assets/6291329/16409202/efcfa702-3d4e-11e6-9ab5-fe3822605b03.png)

**Comment by kura** [comment]
Apologies for the delay in responding. That should be fixed in new versions, previously the assets plugin was required, now it is optional.
