### ISSUE TITLE
GOOGLE CHROMEはUSAからhttpでhttps://kura.gg/eevee/のURLを”click"する時にHSTS alert

### ISSUE THREAD

**Issue by jculpon** [kura/eevee#15]
When using the eevee theme available from getpelican/official source to push to a personal github pages project using http but not https (example: jculpon.github.io), GOOGLE CHROME latest throws a strict transport security warning realted to  the common name of kura.gg being invalid.

# STEPS TO REPRODUCE
1. Visit a personal (not project) github pages page hosted via HTTP not HTTPS. Example link: (jculpon.github.io)[http://jculpon.github.io]
2. Observe that the link to the eevee theme directs to https://kura.io/eevee/ (which should be correct in RELATIVE or NOT RELATIVE URL mode in pelican/pelican theme development)
3. Observe HSTS error in GOOGLE CHROME (tested version: Version 103.0.5060.114 (Official Build) (x86_64) macOS 11.6.7 (20G630))
4. Note big scary warning screen which chrome (not chromium) will not let you skip by. (see attached image)

# EXPECTED BEHAVIOR
1. Clicking on https://kura.io/eevee/ should not result in strict transport security warnings.

# IMAGE ATTACHMENT
[tk]

**Comment by jculpon** [comment]
Double checked this in Firefox latest (non-beta) chanel and getting the same error, guessing it's a redirection issue with kura.gg

**Comment by kura** [comment]
Apologies for the late reply, I did not get a notification that this issue existed.

It looks like the version in pelican_themes is old, I'll fire off a pull request to update the submodule in getpelican/pelican-themes

**Comment by kura** [comment]
This has been done. https://github.com/getpelican/pelican-themes/commit/6dd54f54e14b12561abeda1567119d25d8a2ce0f

**Comment by jculpon** [comment]
Apologies for ABBREV, traveling: thanks for taking care of this, kuraさん.
Will confirm on my end when back at a trustworthy python install!
🦊🏳️‍🌈⛈🐍🦆🖖🏽👾

**Comment by kura** [comment]
No problem. The other option would be to install the theme directly from this repo, which is my preferred method of usage.

**Comment by jculpon** [comment]
On Thu, Aug 18, 2022 at 1:28 PM Kura ***@***.***> wrote:

> No problem. The other option would be to install the theme directly from
> this repo, which is my preferred method of usage.
>
Yeah, for my personal things that would be better but I use my blog
template via the @PunchElvis org to bootstrap others who take over support,
so I have to have one that can do a clean recursive pull with submodules
even if I muck up a github vs gitlab vs private repo bridge
